/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cowsandbulls;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Karthik Perumal
 */
public class helpFrame extends javax.swing.JFrame {

    /**
     * Creates new form helpFrame
     */
    public helpFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        helpBox = new javax.swing.JComboBox();
        closeB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        HelpText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        HelpText1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HELP");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("cowicon1.jpg")));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        helpBox.setFont(new java.awt.Font("Trebuchet MS", 3, 11)); // NOI18N
        helpBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RULES", "MODES", "LEVELS", "DISCLAIMER", "ABOUT" }));
        helpBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBoxActionPerformed(evt);
            }
        });

        closeB.setText("CLOSE");
        closeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBActionPerformed(evt);
            }
        });

        HelpText.setEditable(false);
        HelpText.setBackground(new java.awt.Color(0, 0, 0));
        HelpText.setColumns(1);
        HelpText.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        HelpText.setForeground(new java.awt.Color(255, 255, 255));
        HelpText.setRows(10);
        HelpText.setWrapStyleWord(true);
        HelpText.setBorder(new javax.swing.border.MatteBorder(null));
        HelpText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(HelpText);

        HelpText1.setEditable(false);
        HelpText1.setBackground(new java.awt.Color(0, 0, 0));
        HelpText1.setColumns(1);
        HelpText1.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        HelpText1.setForeground(new java.awt.Color(255, 255, 255));
        HelpText1.setRows(10);
        HelpText1.setWrapStyleWord(true);
        HelpText1.setBorder(new javax.swing.border.MatteBorder(null));
        HelpText1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(HelpText1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cowsandbulls/grassbackground.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(closeB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(helpBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(helpBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(closeB)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void helpBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBoxActionPerformed
        // TODO add your handling code here:
        int a=helpBox.getSelectedIndex();
        switch(a)
        {
            case 0: HelpText.setText(null);
                    HelpText.append(" Guess a 4 or 5 letter English Word with distinct letters.\n Cow means you have guessed a letter correctly\n but in a wrong positon."
                            + "\n Bull means you have guessed a letter correctly\n in the right position.\n Make guesses and find out the word depending\n on the number of cows and bulls.");
                    break;
            case 1: HelpText.setText(null);
                    HelpText.append(" FREESTYLE - No Timer or Count involved.\n Take infinite guesses to find the word.\n\n TIMER - You are given 5 minutes time to find the word. \n You can take infinite guesses.\n\n COUNTER - You are given 10 guesses to find the word.\n You can take infinite time. \n\n SEQUENCE - You are given 5 minutes time and 10 guesses.\n Find the word within this and you can move on to the next word.\n Try to get your name on the leaderboard by getting a high score\n");
                    break;
                
            case 2: HelpText.setText(null);
                    HelpText.append(" WORD LEVELS\n\n 4 LETTER - Only 4 Letter Words\n\n 5 LETTER - Only 5 Letter Words\n\n\n DIFFICULTY LEVELS\n\n EASY - For the amateur gamer\n\n NORMAL - For Everyone\n\n HARD - For the vocabulary experts");
                    break;
            case 3: HelpText.setText(null);
                    HelpText.append("The game does not intend to hurt any sentiments\n - religious, communal or personal.\n\n The reference made to 'COWS' and 'BULLS' is purely figurative.\n");
                    break;
            case 4: HelpText.setText(null);
                    HelpText.append(" COWS 'N' BULLS\n\n VERSION - 1.0\n\n DEVELOPERS - CODE GAMES\n\n \u00a9 CODE GAMES , 2013");
                    break;
        }
    }//GEN-LAST:event_helpBoxActionPerformed

    private void closeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBActionPerformed
        // TODO add your handling code here:
        WindowEvent wev = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(wev);
    }//GEN-LAST:event_closeBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new helpFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea HelpText;
    private javax.swing.JTextArea HelpText1;
    private javax.swing.JButton closeB;
    private javax.swing.JComboBox helpBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
